# Site settings
title: Lasso Takes a Second Look
description: Examples for Early Music Essay
baseurl: ""  # Leave empty for username.github.io repos
url: "https://RichardFreedman.github.io"

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Process HTML files automatically
defaults:
  - scope:
      path: "*.html"
    values:
      layout: none

# Collections
collections:
  visualizations:
    output: true
    permalink: /:collection/:path/

# Exclude files
exclude:
  - "node_modules"
  - "vendor/bundle"
  - "vendor/cache"
  - ".ruby-gemset"
  - ".rbenv-version"
  - "Gemfile"
  - "Gemfile.lock"
  - "README.md"